module Menu where

--Para limpar a tela
limpaTela = putStrLn "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

--Menu Inicial
inicio = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +                                     +"
		putStrLn " +  1. Soma                            +" 
		putStrLn " +  2. Subtração                       +"
		putStrLn " +  3. Multiplicação                   +"
		putStrLn " +  4. Fatorial                        +"
		putStrLn " +  5. Exponencial                     +"
		putStrLn " +  6. Logaritmo Natural               +"
		putStrLn " +  7. Media                           +"
		putStrLn " +  8. Esqucao de 2º                   +"
		putStrLn " +  9. MMC                             +"
		putStrLn " +  10. MDC                            +"
		putStrLn " +  11. Quadrado                       +"
		putStrLn " +  12. Ajuste Linear                  +"
		putStrLn " +  13. Ajuste Parabolico              +"
		putStrLn " +  14. Ajuste Hiperbolico             +"
		putStrLn " +  15. Ajuste Logaritmico             +"
		putStrLn " +  0. Sair                            +" 
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n" 

--Menu Continuar
continuar = do	putStrLn "\nPrecione ENTER para continuar!\n"

--Menu Sair
menusair = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +                                     +"
		putStrLn " +   Deseja realmenter sair?           +"
		putStrLn " +                                     +"
		putStrLn " +  1. Sim                             +"
		putStrLn " +  2. Não                             +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"  		

--Menu Soma
menusoma = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +       Para realizar a Soma          +"
		putStrLn " +        dos numeros digite:          +"
		putStrLn " +   somaLista [<numeros_desejados>]   +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +        somaLista [1,2,3,4]          +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"		

--Menu Subtração
menusub = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +       Para realizar a Subtracao     +"
		putStrLn " +          dos numeros digite:        +"
		putStrLn " +   subtraiValor <numero1> <numero2>  +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +           subtraiValor 4 2          +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu Multiplicação
menumult = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +    Para realizar a Multiplixação    +"
		putStrLn " +         dos numeros digite:         +"
		putStrLn " +multiplicaLista [<numeros_desejados>]+"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +      multiplicaLista [1,2,3,4]      +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu Fatorial
menufat = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +       Para realizar a Fatorial      +"
		putStrLn " +         de um numero digite:        +"
		putStrLn " +     fatorial <numeros_desejados>    +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +             fatorial 10             +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu Exponencial
menuexp = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +     Para realizar a Exponencial     +"
		putStrLn " +        dos numeros digite:          +"
		putStrLn " +    exponencial <base> <expoente>    +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +         exponencial 2 4             +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu LN
menuln = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +         Para realizar a LN          +"
		putStrLn " +         dos numeros digite:         +"
		putStrLn " +    logLista [<numeros_desejados>]   +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +          logLista [1,2,3,4]         +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu Média
menumedia = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +       Para realizar a Media         +"
		putStrLn " +        dos numeros digite:          +"
		putStrLn " +     media [<numeros_desejados>]     +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +           media [1,2,3,4]           +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu Equação de 2ª grau
menuequa = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +   Para realizar uma Equacao de 2º   +"
		putStrLn " +              igite:                 +"
		putStrLn " +   calculaSolQuadratica <a> <b> <c>  +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +      calculaSolQuadratica 2 7 5     +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu MMC
menummc = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +         Para realizar o MMC         +"
		putStrLn " +               digite:               +"
		putStrLn " +    calculaMmc <numero1> <numero2>   +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +           calculaMmc 25 75          +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu MDC
menumdc = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +         Para realizar o MDC         +"
		putStrLn " +               digite:               +"
		putStrLn " +    calculaMdc <numero1> <numero2>   +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +           calculaMdc 25 75          +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

--Menu Função Quadratica
menuquad = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +     Para realizar a Quadrado        +"
		putStrLn " +        dos numeros digite:          +"
		putStrLn " + quadradoLista [<numeros_desejados>] +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +       quadradoLista [1,2,3,4]       +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
		
--Menu Aproximação Linear
menualin = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " + Para realizar a Aproximação Linear  +"
		putStrLn " +        dos numeros digite:          +"
		putStrLn " + aproxLinear ([numeros1],[numeros2]) +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +      aproxLinear ([1,2],[3,4])      +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
		
--Menu Aproximação Parabolica
menuapar = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +     Para realizar a Aproximação     +"
		putStrLn " +   Parabolica dos numeros digite:    +"
		putStrLn " + aproxQuadra ([numeros1],[numeros2]) +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +      aproxQuadra ([1,2],[3,4])      +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
		
--Menu Aproximação Hiperbolica
menuahip = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +     Para realizar a Aproximação     +"
		putStrLn " +   Hiperbolica dos numeros digite:   +"
		putStrLn " + aproxHiperb ([numeros1],[numeros2]) +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +      aproxHiperb ([1,2],[3,4])      +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
		
--Menu Aproximação Logaritca
menualog = do 	putStrLn " \n"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +           Seja Bem-Vindo            +"
		putStrLn " +       -Calculadora Funcional-       +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +     Para realizar a Aproximação     +"
		putStrLn " +    Logaritca dos numeros digite:    +"
		putStrLn " +   aproxLog ([numeros1],[numeros2])  +"
		putStrLn " +     Observe o exemplo a seguir:     +"
		putStrLn " +       aproxLog ([1,2],[3,4])        +"
		putStrLn " +  O resultado aparecerá em seguida   +"
		putStrLn " +                                     +"
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
		putStrLn " +Ao finalizar, digite 'main' novamente+"	
		putStrLn " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"

